name: 'Terraform'

on:
  push:
    branches:
    - master
     paths:
     - tutorial5/app
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform format check
      run: terraform fmt -check tutorial3/loadbalance/
      
    - name: Terraform version check
      run: terraform --version

    - name: Terraform init
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN_RO }}
      run: terraform init tutorial3/loadbalance/
      
    - name: Terraform plan
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN_RO }}
        TF_VAR_ssh_fingerprint: ${{ secrets.SSH_FINGERPRINT }}
      run: terraform plan tutorial3/loadbalance/

